-- GENERATED BY SANGEN -- DO NOT HAND-EDIT (regenerated on every export)
-- ^ kScenarioGeneratedFileBannerLine (ScenarioScript_DataLua_IO.h, STEP70), duplicated here as
-- plain text since this is a non-C++ resource file -- kept in lockstep MANUALLY with the C++
-- constant; the acceptance test below is the only thing that catches drift.
--
-- SanGenScenarioRuntime.lua -- SANGEN-OWNED, BUNDLED RESOURCE (`ARCH_15_04_ThreeFileOnDiskShape.md` §15.4,
-- MAP_SCENARIO_SPEC.md §2). This file's CONTENT is byte-identical across every map that uses the
-- Map Scenario system -- it carries the generic matching/apply/naval-spawn algorithm only, NEVER
-- any per-map data. SanGen copies this exact text, verbatim, into each map's own
-- <MapName>_Scenarios_Runtime.lua inside LJ/lua/maps/<MapName>/ on every export
-- (ScenarioScript_Export_IO, STEP71) -- the ONLY thing that ever varies between maps is the
-- copy's OWN FILENAME (map-prefixed), never a byte of this text.
--
-- Ported and generalized from the live, in-game-confirmed reference
-- (Pandemonium Isthmus_Scenarios_Script.lua + _data.lua's BuildSlotPattern) so ZERO map-specific
-- data remains: every per-map value below arrives from the generated sibling
-- <MapName>_Scenarios_Data.lua, Import()'d below.
--
-- MUST stay a GLOBAL table (`Scenario = {}`, never `local`) -- Import() (common/systems/import.lua)
-- captures only a file's GLOBAL variables, never its `return` value; a `local`-scoped module
-- silently yields none of its fields through Import(), with no error (MAP_SCENARIO_SPEC.md §3 --
-- this cost a full live debugging session, do not regress it).
Scenario = {}

-- ============================================================================
-- Locate and Import() the sibling per-map data file. RULING (STEP72 §0): MapUtils.GetMapName()
-- self-discovery, NOT a new _data.lua argument -- Scenario.ResolveAndApply's signature is
-- `ARCH_15_10_SlotPatternConstructionMoves.md` §15.10 ratified law with no room for a fifth argument.
--
-- ⚠️ ATTENTION -- UNCONFIRMED LIVE BEHAVIOR. MapUtils.GetMapName() is a confirmed engine API
-- (MODDING_SCRIPTING_SPEC.md's "Scripting API seen" list), but its exact return value at THIS
-- point in the load sequence (during _data.lua's own top-level Import() of this file, itself
-- during LoadMapData()) -- and whether its spelling matches the "<MapName>" folder-name
-- convention exactly, including spaces (e.g. "Pandemonium Isthmus") -- has not been independently
-- live-verified for this call site. IF THE Import() BELOW FAILS ("File doesn't exist") IN A REAL
-- MAP LOAD, THIS IS THE FIRST PLACE TO LOOK.
local currentMapName = MapUtils.GetMapName()
local ScenarioData = Import("maps/" .. currentMapName .. "/" .. currentMapName .. "_Scenarios_Data.lua")

local PATTERN_SCENARIOS   = ScenarioData.PATTERN_SCENARIOS
local COUNT_SCENARIOS     = ScenarioData.COUNT_SCENARIOS
local DEFAULT_SCENARIO    = ScenarioData.DEFAULT_SCENARIO
local MAX_ARMY_SLOT_COUNT = ScenarioData.MAX_ARMY_SLOT_COUNT

-- ⚠️ GAP, FLAGGED NOT INVENTED (`ARCH_15_10_SlotPatternConstructionMoves.md` §15.10 point 3): no ratified renderer anywhere in the pack
-- emits ARMY_ID_TO_NAME/KNOWN_ALLOY_MARKERS into <MapName>_Scenarios_Data.lua yet. This runtime
-- reads them here because the "occupancy"/"explicit" alloyMode branches below NEED them. Until the
-- follow-up ticket adds their rendering, both are nil on every real map.
--
-- FAIL LOUD, NEVER SILENTLY. A missing roster must be an obvious, logged failure -- NOT an `or {}`
-- fallback. With an empty-table fallback the alloy-deletion loops iterate nothing and quietly do
-- nothing: every alloy marker on the map survives for every composition, with no error anywhere.
-- That is indistinguishable in-game from "the scenario system isn't running at all," and it is a
-- REAL OBSERVED SYMPTOM from live testing ("all alloy spawns entire map") -- exactly the class of
-- silent-wrong-result Constitution §6 forbids. The guard below states the problem in the log and
-- refuses to pretend the roster is empty.
local ARMY_ID_TO_NAME     = ScenarioData.ARMY_ID_TO_NAME
local KNOWN_ALLOY_MARKERS = ScenarioData.KNOWN_ALLOY_MARKERS

-- True only when BOTH rosters are present. Read once here; every alloy branch below consults it
-- rather than re-testing, so the warning is emitted exactly once per apply, not once per army.
local bAlloyRosterAvailable = (ARMY_ID_TO_NAME ~= nil) and (KNOWN_ALLOY_MARKERS ~= nil)

-- Identity rotation/scale for any alloy marker this file creates fresh -- matches every marker
-- already in the .sanmap (none use anything else), ported verbatim from the live reference.
local IDENTITY_ROTATION = { w = 1.0, x = 0.0, y = 0.0, z = 0.0 }
local IDENTITY_SCALE = { x = 1.0, y = 1.0, z = 1.0 }

-- ============================================================================
-- Slot-pattern construction (`ARCH_15_10_SlotPatternConstructionMoves.md` §15.10 -- moved here from _data.lua). Ported verbatim from
-- the reference _data.lua's own BuildSlotPattern, hardcoded 16 replaced by MAX_ARMY_SLOT_COUNT.
-- ============================================================================
local function BuildSlotPattern(players, maxArmySlotCount)
    local chars = {}
    for i = 1, maxArmySlotCount do
        chars[i] = "-"
    end
    for _, player in ipairs(players) do
        if player.armyID and player.armyID >= 1 and player.armyID <= maxArmySlotCount then
            chars[player.armyID] = (player.playerType == PlayerType.AI) and "A" or "h"
        end
    end
    return table.concat(chars)
end

-- ============================================================================
-- Declarative condition evaluator -- NEW code, no equivalent in the live reference. The live
-- reference's COUNT_SCENARIOS carried Lua closures (match = function(t,h,a,pattern) ... end); the
-- ratified SanGen-rendered contract is DATA instead (STEP69/STEP70): an array of
-- {field, comparator, value} triples, AND'd. field/comparator spellings are keyed off VERBATIM
-- against Params::ScenarioCountField/Params::ScenarioComparator's own rendered JSON spellings.
-- ============================================================================
local function EvaluateScenarioCondition(condition, total, humanCount, aiCount)
    local fieldValue
    if condition.field == "Total" then
        fieldValue = total
    elseif condition.field == "HumanCount" then
        fieldValue = humanCount
    elseif condition.field == "AiCount" then
        fieldValue = aiCount
    else
        Warn("SANGEN: scenario condition named unknown field '"..tostring(condition.field).."' -- treated as non-matching.")
        return false -- unknown field -- fail CLOSED, never matches, never a crash
    end

    if condition.comparator == "Equal" then
        return fieldValue == condition.value
    elseif condition.comparator == "NotEqual" then
        return fieldValue ~= condition.value
    elseif condition.comparator == "GreaterThan" then
        return fieldValue > condition.value
    elseif condition.comparator == "GreaterOrEqual" then
        return fieldValue >= condition.value
    elseif condition.comparator == "LessThan" then
        return fieldValue < condition.value
    elseif condition.comparator == "LessOrEqual" then
        return fieldValue <= condition.value
    else
        Warn("SANGEN: scenario condition named unknown comparator '"..tostring(condition.comparator).."' -- treated as non-matching.")
        return false -- unknown comparator -- fail CLOSED
    end
end

-- Conjunction only (AND) -- `ARCH_15_05_ParamsScenariosType.md` §15.5's ruling. An empty conditions list is vacuously true,
-- matching Params::CountScenario::conditions' flat std::vector carrying no OR/grouping structure.
local function EvaluateScenarioConditions(conditions, total, humanCount, aiCount)
    for _, condition in ipairs(conditions) do
        if not EvaluateScenarioCondition(condition, total, humanCount, aiCount) then
            return false
        end
    end
    return true
end

-- ============================================================================
-- Three-tier matching (MAP_SCENARIO_SPEC.md §4). Ported verbatim in STRUCTURE from the live
-- reference's FindMatchingScenario -- the TIER 2 body now calls EvaluateScenarioConditions instead
-- of a per-scenario closure; that is the only change.
-- ============================================================================
local function FindMatchingScenario(total, humanCount, aiCount, slotPattern)
    for _, scenario in ipairs(PATTERN_SCENARIOS) do
        if scenario.pattern == slotPattern then
            return scenario
        end
    end
    for _, scenario in ipairs(COUNT_SCENARIOS) do
        -- pcall-wrapped per MAP_SCENARIO_SPEC.md §4: a throwing evaluation is swallowed (falls
        -- through to the next candidate), not fatal -- preserved from the reference's own
        -- per-closure pcall, now wrapping the shared evaluator instead.
        local evalOk, matched = pcall(EvaluateScenarioConditions, scenario.conditions, total, humanCount, aiCount)
        if evalOk and matched then
            return scenario
        end
    end
    return DEFAULT_SCENARIO
end

-- ============================================================================
-- Applies a matched scenario's spawn/alloy data (MAP_SCENARIO_SPEC.md §5, all four alloyMode
-- branches). Must run before RunMapSetup/CreateArmies read the same tables.
--
-- ⚠️ STRUCTURAL PORT, not a byte-for-byte copy of the reference's loop bodies: the reference's
-- scenario.spawns/scenario.alloys were tables KEYED BY ARMY NAME ({ ARMY_01 = {...}, ... }). The
-- SanGen-rendered contract (ScenarioScript_DataLua_IO, STEP70) instead emits
-- Params::ScenarioSpawn/Params::ScenarioAlloyOverride as FLAT ARRAYS OF ROWS, each row carrying
-- its own armyName field -- a real shape difference, not cosmetic. Every loop below ipairs() the
-- flat array and reads armyName/markerName off each row.
-- ============================================================================
local function ApplyScenario(scenario, total, slotPattern)
    if scenario.spawns then
        local spawnTransforms = GameInfo.MapData.markers and GameInfo.MapData.markers.Spawn
            and GameInfo.MapData.markers.Spawn.transforms
        if spawnTransforms then
            for _, spawnRow in ipairs(scenario.spawns) do
                if spawnTransforms[spawnRow.armyName] then
                    spawnTransforms[spawnRow.armyName].position.x = spawnRow.x
                    spawnTransforms[spawnRow.armyName].position.y = spawnRow.y
                    spawnTransforms[spawnRow.armyName].position.z = spawnRow.z
                end
            end
        end
    end

    local alloyTransforms = GameInfo.MapData.markers and GameInfo.MapData.markers.Alloys
        and GameInfo.MapData.markers.Alloys.transforms
    if alloyTransforms then
        -- FAIL LOUD on a missing roster (see the bAlloyRosterAvailable comment above). "explicit"
        -- and "occupancy" BOTH delete markers via the roster; without it they would silently
        -- delete nothing and leave every alloy on the map. "keepAll" and "delta" never touch the
        -- roster, so they are unaffected and must NOT be blocked by this guard.
        local bModeNeedsRoster = (scenario.alloyMode == "explicit") or (scenario.alloyMode == "occupancy")
        if bModeNeedsRoster and not bAlloyRosterAvailable then
            Warn("SANGEN: scenario '"..tostring(scenario.name).."' uses alloyMode '"..
                 tostring(scenario.alloyMode).."', which needs the per-army alloy roster "..
                 "(ARMY_ID_TO_NAME / KNOWN_ALLOY_MARKERS) -- but the generated "..
                 "<MapName>_Scenarios_Data.lua did not supply it. NO ALLOY MARKERS WILL BE "..
                 "REMOVED: every alloy on the map will remain visible for every composition. "..
                 "This is a MISSING-DATA bug in the export, not a map-authoring choice.")
        end

        if scenario.alloyMode == "explicit" and bAlloyRosterAvailable then
            local mentionedArmies = {}
            for _, alloyRow in ipairs(scenario.alloys or {}) do
                mentionedArmies[alloyRow.armyName] = true
                if not alloyTransforms[alloyRow.markerName] then
                    alloyTransforms[alloyRow.markerName] = { rotation = IDENTITY_ROTATION, scale = IDENTITY_SCALE, position = {} }
                end
                alloyTransforms[alloyRow.markerName].position.x = alloyRow.x
                alloyTransforms[alloyRow.markerName].position.y = alloyRow.y
                alloyTransforms[alloyRow.markerName].position.z = alloyRow.z
            end
            for armyName, markerNames in pairs(KNOWN_ALLOY_MARKERS) do
                if not mentionedArmies[armyName] then
                    for _, markerName in ipairs(markerNames) do
                        alloyTransforms[markerName] = nil
                    end
                end
            end
        elseif scenario.alloyMode == "occupancy" and bAlloyRosterAvailable then
            -- `ARCH_15_10_SlotPatternConstructionMoves.md` §15.10 point 3 fix: iterate the AUTHORED ROSTER directly, never a hardcoded
            -- numeric range (the reference's own "for armyId = 1, 4" was one of the three
            -- independent hardcodes this whole ticket family exists to remove).
            for armyId, armyName in pairs(ARMY_ID_TO_NAME) do
                if slotPattern:sub(armyId, armyId) == "-" then
                    for _, markerName in ipairs(KNOWN_ALLOY_MARKERS[armyName] or {}) do
                        alloyTransforms[markerName] = nil
                    end
                    Log("SANGEN: "..tostring(armyName).." has no player -- its alloy markers removed before RunMapSetup.")
                end
            end
        elseif scenario.alloyMode == "delta" then
            -- Unlike "explicit", silence here is NOT a delete instruction -- only alloysToAdd/
            -- alloysToRemove are applied (MAP_SCENARIO_SPEC.md §5).
            for _, addRow in ipairs(scenario.alloysToAdd or {}) do
                if not alloyTransforms[addRow.markerName] then
                    alloyTransforms[addRow.markerName] = { rotation = IDENTITY_ROTATION, scale = IDENTITY_SCALE, position = {} }
                end
                alloyTransforms[addRow.markerName].position.x = addRow.x
                alloyTransforms[addRow.markerName].position.y = addRow.y
                alloyTransforms[addRow.markerName].position.z = addRow.z
            end
            for _, removeRow in ipairs(scenario.alloysToRemove or {}) do
                alloyTransforms[removeRow.markerName] = nil
            end
        end
        -- "keepAll": no deletion -- every known marker stays exactly as the .sanmap has it baked.
    end

    Log("SANGEN: scenario '"..tostring(scenario.name).."' applied ("..total.." occupied slot(s)).")
end

-- Bridges ResolveAndApply -> SpawnNavalFleets: the matched scenario's OWN navalFleet table
-- (`ARCH_15_05_ParamsScenariosType.md` §15.5 -- navalFleet is per-scenario, not a file-scoped constant the way the live
-- reference's NAVAL_FLEET/NAVAL_POND_SIDE_BY_ARMY/NAVAL_SIDE_BIAS_DISTANCE were). Module-local
-- state is required because Scenario.SpawnNavalFleets(area)'s signature (MAP_SCENARIO_SPEC.md §3,
-- unchanged by `ARCH_15_10_SlotPatternConstructionMoves.md` §15.10) carries only `area` -- this is how the later, NewThread-deferred
-- call learns which scenario matched.
local currentNavalFleet = nil

function Scenario.ResolveAndApply(total, humanCount, aiCount, playersInformation)
    local slotPattern = BuildSlotPattern(playersInformation, MAX_ARMY_SLOT_COUNT)
    local matchedScenario = FindMatchingScenario(total, humanCount, aiCount, slotPattern)
    local chosenArea, navyEnabled = matchedScenario.area, matchedScenario.navy
    currentNavalFleet = matchedScenario.navalFleet
    ApplyScenario(matchedScenario, total, slotPattern)

    Log(string.format(
        "SANGEN: %d occupied slot(s) (%d human, %d AI, pattern=%s) -> scenario=%s navy=%s, playable area x=%d y=%d w=%d h=%d",
        total, humanCount, aiCount, slotPattern, tostring(matchedScenario.name),
        tostring(navyEnabled), chosenArea.x, chosenArea.y, chosenArea.width, chosenArea.height))

    return chosenArea, navyEnabled
end

-- ============================================================================
-- Naval fleet spawning (MAP_SCENARIO_SPEC.md §5.1). Spiral/grid helpers and the tuning constants
-- below are ALGORITHM TUNING CONSTANTS, ported byte-for-byte from the reference and NEVER exposed
-- as Params::Scenarios fields (`ARCH_15_05_ParamsScenariosType.md` §15.5) -- they never vary per map, unlike
-- NAVAL_FLEET/NAVAL_POND_SIDE_BY_ARMY/NAVAL_SIDE_BIAS_DISTANCE, now read per-scenario off
-- currentNavalFleet instead of as file-scoped globals.
-- ============================================================================
local NAVAL_BATCH_SIZE = 100
local NAVAL_SPIRAL_STEP = 2.5
local NAVAL_SPIRAL_MAX_TRIES = 400
local NAVAL_GAP = 1.5
local NAVAL_DEFAULT_FOOTPRINT = { x = 6, y = 6 }
local NAVAL_GRID_CELL = 16
local NAVAL_GIVE_UP_AFTER_MISSES = 15

local function NavalSpiralXZ(n)
    local k = math.ceil((math.sqrt(n) - 1) / 2)
    local t = 2 * k + 1
    local m = t ^ 2
    t = t - 1
    if n >= m - t then
        return k - (m - n), -k
    else
        m = m - t
    end
    if n >= m - t then
        return -k, -k + (m - n)
    else
        m = m - t
    end
    if n >= m - t then
        return -k + (m - n), k
    else
        return k, k - (m - n - t)
    end
end

local function NavalNewGrid() return { cells = {} } end
local function NavalGridKey(x, z) return math.floor(x / NAVAL_GRID_CELL) * 100000 + math.floor(z / NAVAL_GRID_CELL) end
local function NavalGridAdd(grid, x, z, r)
    local key = NavalGridKey(x, z)
    local bucket = grid.cells[key]
    if not bucket then
        bucket = {}
        grid.cells[key] = bucket
    end
    bucket[#bucket + 1] = { x = x, z = z, r = r }
end
local function NavalGridHasNearby(grid, x, z, extraRadius)
    local span = math.ceil((6 + extraRadius) / NAVAL_GRID_CELL) + 1
    local cx, cz = math.floor(x / NAVAL_GRID_CELL), math.floor(z / NAVAL_GRID_CELL)
    for dx = -span, span do
        for dz = -span, span do
            local bucket = grid.cells[(cx + dx) * 100000 + (cz + dz)]
            if bucket then
                for _, e in ipairs(bucket) do
                    local ddx, ddz = x - e.x, z - e.z
                    local minDist = e.r + extraRadius
                    if (ddx * ddx + ddz * ddz) < (minDist * minDist) then
                        return true
                    end
                end
            end
        end
    end
    return false
end

local function NavalIsInsideArea(x, z, area)
    return x >= area.x and x <= area.x + area.width and z >= area.y and z <= area.y + area.height
end

local function NavalFindSpot(occupiedGrid, area, idealX, idealZ, radius, waterLevel)
    for n = 1, NAVAL_SPIRAL_MAX_TRIES do
        local gx, gz = NavalSpiralXZ(n)
        local x = idealX + gx * NAVAL_SPIRAL_STEP
        local z = idealZ + gz * NAVAL_SPIRAL_STEP

        if NavalIsInsideArea(x, z, area) and not NavalGridHasNearby(occupiedGrid, x, z, radius) then
            local errorCode, height = Engine.SampleTerrainHeightFromCell(EngineClasses.int2(math.floor(x), math.floor(z)))
            if errorCode == EngineErrorCode.Success and height < waterLevel then
                return x, z, waterLevel
            end
        end
    end
    return nil
end

local function NavalPlaceDeficitMarkers(armyIndex, originX, originZ, missedCount)
    local count = math.min(missedCount, 10)
    for i = 1, count do
        local col = (i - 1) % 5
        local row = math.floor((i - 1) / 5)
        local x = originX + 3 + col * 2
        local z = originZ + 3 + row * 2
        local errorCode, height = Engine.SampleTerrainHeightFromCell(EngineClasses.int2(math.floor(x), math.floor(z)))
        if errorCode == EngineErrorCode.Success then
            pcall(CreateUnit, armyIndex, "uel1001", EngineClasses.float3(x, height, z))
        end
    end
end

-- Only called for a matched scenario with navy == true. Must run after RunMapSetup (Armies must be
-- populated) -- the orchestrator's single NewThread callback owns this ordering
-- (MAP_SCENARIO_SPEC.md §7); this file never creates its own NewThread (only one is honored per
-- script).
function Scenario.SpawnNavalFleets(area)
    local navalFleet = currentNavalFleet or { fleet = {}, pondSideByArmy = {}, sideBiasDistance = 0 }

    local pondSideByArmyLookup = {}
    for _, sideRow in ipairs(navalFleet.pondSideByArmy or {}) do
        pondSideByArmyLookup[sideRow.armyName] = sideRow.side
    end

    local _, hasWaterResult = Engine.HasWater()
    if not hasWaterResult then
        Log("SANGEN: map reports no water -- skipping naval fleet spawn.")
        return
    end
    local _, waterLevel = Engine.GetWaterLevel()

    local occupied = NavalNewGrid()
    local sinceYield = 0
    local totalPlaced, totalMissed = 0, 0

    for armyIndex, army in pairs(Armies) do
        if not army.lobbyOptions.isEmptySlot then
            local armyOk, armyErr = pcall(function()
                local spawnMarker = GameInfo.MapData.markers.Spawn
                    and GameInfo.MapData.markers.Spawn.transforms
                    and GameInfo.MapData.markers.Spawn.transforms[army.name]

                local startX = (spawnMarker and spawnMarker.position.x) or (area.x + area.width * 0.5)
                local startZ = (spawnMarker and spawnMarker.position.z) or (area.y + area.height * 0.5)

                local primarySide = pondSideByArmyLookup[army.name] or 1
                local searchOriginX = startX + primarySide * navalFleet.sideBiasDistance

                local armyPlaced, armyMissed = 0, 0

                for _, fleetEntry in ipairs(navalFleet.fleet or {}) do
                    local template = __Templates.Units[fleetEntry.templateIdentifier]
                    local footprint = (template and (template.skirtSize or template.footprint)) or NAVAL_DEFAULT_FOOTPRINT
                    local radius = math.max(footprint.x, footprint.y) * 0.5 + NAVAL_GAP

                    local consecutiveMisses = 0
                    for i = 1, fleetEntry.count do
                        if consecutiveMisses >= NAVAL_GIVE_UP_AFTER_MISSES then
                            local remaining = fleetEntry.count - i + 1
                            armyMissed = armyMissed + remaining
                            break
                        end

                        local x, z, h = NavalFindSpot(occupied, area, searchOriginX, startZ, radius, waterLevel)
                        if x then
                            local createOk, unit = pcall(CreateUnit, armyIndex, fleetEntry.templateIdentifier, EngineClasses.float3(x, h, z))
                            if createOk and unit then
                                NavalGridAdd(occupied, x, z, radius)
                                armyPlaced = armyPlaced + 1
                                consecutiveMisses = 0
                            else
                                armyMissed = armyMissed + 1
                                consecutiveMisses = consecutiveMisses + 1
                            end
                        else
                            armyMissed = armyMissed + 1
                            consecutiveMisses = consecutiveMisses + 1
                        end

                        sinceYield = sinceYield + 1
                        if sinceYield >= NAVAL_BATCH_SIZE then
                            sinceYield = 0
                            WaitTicks(1)
                        end
                    end
                end

                totalPlaced = totalPlaced + armyPlaced
                totalMissed = totalMissed + armyMissed

                Log(string.format("SANGEN: army %s naval spawn -- placed %d, missed %d.", tostring(army.name), armyPlaced, armyMissed))

                if armyMissed > 0 then
                    NavalPlaceDeficitMarkers(armyIndex, startX, startZ, armyMissed)
                end
            end)

            if not armyOk then
                Warn("SANGEN: naval fleet spawn failed for army "..tostring(army.name)..", other armies unaffected: "..tostring(armyErr))
            end
        end
    end

    Log(string.format("SANGEN: naval fleet spawn done -- placed %d, missed %d total.", totalPlaced, totalMissed))
end

return Scenario -- inert (Import() ignores a module's `return`, MAP_SCENARIO_SPEC.md §3) -- kept
                -- only for parity with the live reference's own final line.
