// ScenarioScript_DataLua_IO.h — renders Params::Scenarios (STEP69, `ARCH_15_05_ParamsScenariosType.md` §15.5) into the text of
// the generated <MapName>_Scenarios_Data.lua companion file (`ARCH_15_04_ThreeFileOnDiskShape.md` §15.4, MAP_SCENARIO_SPEC.md
// §2). Layer: IO. Pure, disk-free -- mirrors MapExporter_IO::BuildSanmapJsonText's own shape:
// PARAMS in, complete document text out, no filesystem touched here (that's ScenarioScript_Export_IO,
// STEP71). Composes ONLY LuaTableWriter_IO.h's generic primitives (STEP63) -- never JsonPrimitives_IO,
// never hand-rolled Lua string concatenation outside those primitives (DESIGN_MapScenarioIO_R1.md §1).
//
// Export-only, one-directional (`ARCH_15_03_ExportOnlyLuaRatified.md` §15.3): there is no matching "read this back" function
// anywhere in this file or its .cpp, and there never will be -- do not add one.
#pragma once
#include <string>

namespace SanmapGen {
namespace Params { struct MapRecipe; }
namespace Io {

// The exact literal every SanGen-owned scenario Lua file (this one AND the WO6 Runtime file) opens
// with (`ARCH_15_04_ThreeFileOnDiskShape.md` §15.4 point 2, MAP_SCENARIO_SPEC.md §2.1). SINGLE SOURCE OF TRUTH: STEP71
// (ScenarioScript_Export_IO)'s overwrite-safety check compares an existing file's first line
// against this exact string -- never re-typed as a second literal there. Whoever authors WO6
// (ScenarioScript_RuntimeResource_IO) MUST open the bundled runtime resource's own source text with
// this exact line too -- flagged here for that future ticket.
//
// ASCII-only by deliberate choice (plain "--" rather than an em-dash) -- maximizes grep-safety and
// avoids any encoding ambiguity inside a Lua source comment that different tools/editors may
// re-save under different encodings.
inline constexpr const char* kScenarioGeneratedFileBannerLine =
    "-- GENERATED BY SANGEN -- DO NOT HAND-EDIT (regenerated on every export)";

// recipe.scenarios -> the complete text of <MapName>_Scenarios_Data.lua, including the banner line
// above and the trailing global-table declarations. Pure and total -- never throws, never touches
// the filesystem. Takes the whole MapRecipe (not just Params::Scenarios) for the same reason
// BuildScenariosJson (STEP69) does: recipe.geometry.mapSize is needed for the position Z-flip (§3
// below), and recipe.mapName seeds the file's own header comment.
std::string BuildScenarioDataLuaText(const Params::MapRecipe& recipe);

} // namespace Io
} // namespace SanmapGen
